### PR TITLE
Directory parameter may be a single file

### LINKED ISSUE #14: Option to publish a single file rather than all files in a directory
Hi,

Firstly, thank you for your work on this to date. I work in a relatively large team of APEX developers and am looking at improvements to our workflow. To this end, I have begun work on a VSCode extension similar to @tschf's [odb-task](https://github.com/tschf/odb-task) that uses this package to publish static files.

One thing I noted was that it would be valuable to have the option to publish a single file rather than all files in a directory. Publishing all files at once has two drawbacks:

- Increased upload time
- May overwrite other developers' changes

I am not familiar with ~Java~ Node but I think a straightforward change to [distUpload.js](https://github.com/vincentmorneau/apex-publish-static-files/blob/master/lib/distUpload.js) would make this possible.

Thanks!

### PR DESCRIPTION
**Pull request by tim-lawson**
Fixes #14.

I expect that the [recursive function that checks whether the directory is empty](https://github.com/tslwn/apex-publish-static-files/blob/single-file/index.js#L38-L50) could be simplified, but otherwise I think the changes are minimal. A minor complication that I had not anticipated is that the name of each file is its path relative to the `directory` parameter. I cannot think of an alternative to the [local file name](https://github.com/tslwn/apex-publish-static-files/blob/single-file/lib/distUpload.js#L151-L156) when publishing a single file.

I have tested all combinations of the parameters using the package alone and as part of a VS Code extension (the impetus for this PR).

### CODE REVIEW

**Comment by vincentmorneau** [comment]
Thanks! Before I dive into this, can you check travis CI and fix the warnings: https://travis-ci.org/vincentmorneau/apex-publish-static-files/jobs/502082759

**Comment by tim-lawson** [comment]
Thanks for the heads up - should have known I'd forgotten something.

**Comment by vincentmorneau** [comment]
I merged it but I get a weird outcome.

image

I called the node app with 
```js
_app.publish({
		sqlclPath: 'sql',
		connectString: 'myconnectstring',
		directory: './demo/demo-working/js/app.js',
		appID: 101
	});
```

And the file was uploaded as an absolute path.

Using your approach, I would expect the file to be upload at the root level on the Shared Components - Application Static Files.

Any thoughts?

**Comment by tim-lawson** [comment]
That's surprising - on my machine that case results in the filename `app.js`. I'll have a look at the paths in more detail today.

**Comment by vincentmorneau** [comment]
I should add that this was tested on macOS. Also my test contains a `directory` value which is a relative path to the file (`app.js`), as opposed to being in the same directory as `app.js`

**Comment by tim-lawson** [comment]
I'm on Windows, so I think the issue is that I only handled the Windows file separator [here](https://github.com/tslwn/apex-publish-static-files/commit/ae5ea2845adc8533191f1ad5e5de317dd004ce60#diff-add68a0575db7070965c9554817ea264R155); I think [this change](https://github.com/vincentmorneau/apex-publish-static-files/compare/master...tslwn:single-file) would handle both Unix and Windows paths.

I'll have to set up a Unix VM to be certain, but the PL/SQL returns the same filename for absolute paths of both types. In the meantime if you were able to run that case again for [the branch](https://github.com/tslwn/apex-publish-static-files/tree/single-file), I would appreciate it.

**Comment by vincentmorneau** [comment]
I tested and it is working fine. Thanks a lot. Really appreciate the pull request.

I am looking into adding SSH support before I cut a release. Not sure about the timeline of that feature.

Would you happen to know anything about it?

**Comment by tim-lawson** [comment]
No problem - thanks for testing! I haven't looked into connecting via SSH before but am happy to investigate.

**Pull request merged**
